name: Deploy FastAPI

on:
  push:
    branches:
      - main
      - master

# allow only one process
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432 
  
  # deploy:
  #   runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        # uses: actions/setup-python@v3
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          # python -m pip install --upgrade pip
          # pip install -r requirements.txt
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy App
        run: |
          python manage.py runserver &

      - name: Run migrations
        # env:
          # DATABASE_URL: postgres://django_user:django_password@localhost:5432/django_db
        run: |
          # source venv/bin/activate
          # python manage.py migrate

      - name: Run Tests
        # env:
          # DATABASE_URL: postgres://django_user:django_password@localhost:5432/django_db
        run: |
          source venv/bin/activate
          python manage.py test

      # - name: Check Running Services
      #   run: |
      #     sleep 5  # Wait for the server to start
      #     curl --fail http://localhost:8000/ || exit 1
      #     # http://127.0.0.1:8000/

      # - name: Show Deployed URL
      #   run: echo "Your API is available at https://marut-tandel.github.io/fast_api/.onrender.com"
